name: Commit checks
on: pull_request

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.1.0
  fixup-squash-commits:
    name: Fixup and squash commits
    runs-on: ubuntu-latest
    steps:
      - name: Run check
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
